services:
  github-runner:
    container_name: github-runner
    image: github-runner
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: "no"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RUNNER_MANAGER_TOKEN=
      - RUNNER_NAME=
      - GITHUB_ORG=
