services:
  lfc-runner:
    container_name: lfc-runner
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lfc-runner
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: "no"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RUNNER_MANAGER_TOKEN=
      - RUNNER_NAME=
      - GITHUB_ORG=
